### ISSUE TITLE
Use canonical dotnet project structure

### ISSUE THREAD

**Issue by ehonda** [relaxdays/TestUtilities.Scenarios#88]
Restructure repository contents to adhere to the example given in [this gist](https://gist.github.com/davidfowl/ed7564297c61fe9ab814), which seems to be a well known, widely used structure.

**Comment by Laxynium** [comment]
Hi, could I take this one?

**Comment by ehonda** [comment]
For sure! I have assigned you the PR.

**Comment by ehonda** [comment]
Done via #89
